name: Github actions

run-name: practice run

on:
  - push



jobs:
  
  app_runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: python app.py
      

    