name: Github actions

#Name of action
run-name: practice run

#Event
on:
  - push
  - pull_request


jobs:      

  app_setup:
    runs-on: ubuntu-latest
    steps:

      # include github repo actions
      - uses: actions/checkout@v3

      #setup python environment
      - name: Setup python
        uses: actions/setup-python@v4
        with: 
          python-version: "3.10"
      - run: echo ${{github.actor}}
      - run: python -m pip  install -r requirements.txt
      - run: flake8
      - run: pytest

  docker_setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build . -t flaskapp
